version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.1.3

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

      build:
        docker:
          steps:
            - run: mvn integration-test
            - run:
                name: Send to CodeCov
                command: bash <(curl -s https://codecov.io/bash)
